name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node Package
        run: npm i -f

      - name: Build
        run: npm run build

      - name: Nen_File
        run: cd build && tar -cvf ../build.tar *

      - name: Deploy
        run: curl -X POST http://192.168.1.15:1704/linux/execute -H "Content-Type: application/json" -d '{"command":"cd /home/dai/actions-runner/ && bash test.sh"}'