name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node Package
        run: npm i -f


      - name: Build
        run: npm run build

      - name: Nen_File
        run: cd build && tar -cvf ../build.tar *

      - name: Deploy
        run: cd /home/dai/actions-runner/_work/public_web/public_web && pwd && bash ci_cd.sh